/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GiveawaysIndexRouteImport } from './routes/giveaways.index'
import { Route as FeaturesIndexRouteImport } from './routes/features.index'
import { Route as GiveawaysSlugRouteImport } from './routes/giveaways.$slug'
import { Route as FeaturesNumberRouteImport } from './routes/features.$number'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as FeaturesNumberMagazineRouteImport } from './routes/features.$number.magazine'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminPartnersRouteImport } from './routes/_authenticated/admin.partners'
import { Route as AuthenticatedAdminAnnouncementsRouteImport } from './routes/_authenticated/admin.announcements'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAdminGiveawaysIndexRouteImport } from './routes/_authenticated/admin.giveaways.index'
import { Route as AuthenticatedAdminGiveawaysNewRouteImport } from './routes/_authenticated/admin.giveaways.new'
import { Route as AuthenticatedAdminGiveawaysIdRouteImport } from './routes/_authenticated/admin.giveaways.$id'
import { Route as AuthenticatedAdminFeaturesNewRouteImport } from './routes/_authenticated/admin.features.new'
import { Route as AuthenticatedAdminFeaturesIdRouteImport } from './routes/_authenticated/admin.features.$id'

const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GiveawaysIndexRoute = GiveawaysIndexRouteImport.update({
  id: '/giveaways/',
  path: '/giveaways/',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesIndexRoute = FeaturesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FeaturesRoute,
} as any)
const GiveawaysSlugRoute = GiveawaysSlugRouteImport.update({
  id: '/giveaways/$slug',
  path: '/giveaways/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesNumberRoute = FeaturesNumberRouteImport.update({
  id: '/$number',
  path: '/$number',
  getParentRoute: () => FeaturesRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const FeaturesNumberMagazineRoute = FeaturesNumberMagazineRouteImport.update({
  id: '/magazine',
  path: '/magazine',
  getParentRoute: () => FeaturesNumberRoute,
} as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPartnersRoute =
  AuthenticatedAdminPartnersRouteImport.update({
    id: '/partners',
    path: '/partners',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnnouncementsRoute =
  AuthenticatedAdminAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGiveawaysIndexRoute =
  AuthenticatedAdminGiveawaysIndexRouteImport.update({
    id: '/giveaways/',
    path: '/giveaways/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGiveawaysNewRoute =
  AuthenticatedAdminGiveawaysNewRouteImport.update({
    id: '/giveaways/new',
    path: '/giveaways/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGiveawaysIdRoute =
  AuthenticatedAdminGiveawaysIdRouteImport.update({
    id: '/giveaways/$id',
    path: '/giveaways/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFeaturesNewRoute =
  AuthenticatedAdminFeaturesNewRouteImport.update({
    id: '/features/new',
    path: '/features/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFeaturesIdRoute =
  AuthenticatedAdminFeaturesIdRouteImport.update({
    id: '/features/$id',
    path: '/features/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/features': typeof FeaturesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/features/$number': typeof FeaturesNumberRouteWithChildren
  '/giveaways/$slug': typeof GiveawaysSlugRoute
  '/features/': typeof FeaturesIndexRoute
  '/giveaways/': typeof GiveawaysIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/features/$number/magazine': typeof FeaturesNumberMagazineRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/features/$id': typeof AuthenticatedAdminFeaturesIdRoute
  '/admin/features/new': typeof AuthenticatedAdminFeaturesNewRoute
  '/admin/giveaways/$id': typeof AuthenticatedAdminGiveawaysIdRoute
  '/admin/giveaways/new': typeof AuthenticatedAdminGiveawaysNewRoute
  '/admin/giveaways/': typeof AuthenticatedAdminGiveawaysIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/features/$number': typeof FeaturesNumberRouteWithChildren
  '/giveaways/$slug': typeof GiveawaysSlugRoute
  '/features': typeof FeaturesIndexRoute
  '/giveaways': typeof GiveawaysIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/features/$number/magazine': typeof FeaturesNumberMagazineRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/features/$id': typeof AuthenticatedAdminFeaturesIdRoute
  '/admin/features/new': typeof AuthenticatedAdminFeaturesNewRoute
  '/admin/giveaways/$id': typeof AuthenticatedAdminGiveawaysIdRoute
  '/admin/giveaways/new': typeof AuthenticatedAdminGiveawaysNewRoute
  '/admin/giveaways': typeof AuthenticatedAdminGiveawaysIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/features': typeof FeaturesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit': typeof SubmitRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/features/$number': typeof FeaturesNumberRouteWithChildren
  '/giveaways/$slug': typeof GiveawaysSlugRoute
  '/features/': typeof FeaturesIndexRoute
  '/giveaways/': typeof GiveawaysIndexRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/_authenticated/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/features/$number/magazine': typeof FeaturesNumberMagazineRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/features/$id': typeof AuthenticatedAdminFeaturesIdRoute
  '/_authenticated/admin/features/new': typeof AuthenticatedAdminFeaturesNewRoute
  '/_authenticated/admin/giveaways/$id': typeof AuthenticatedAdminGiveawaysIdRoute
  '/_authenticated/admin/giveaways/new': typeof AuthenticatedAdminGiveawaysNewRoute
  '/_authenticated/admin/giveaways/': typeof AuthenticatedAdminGiveawaysIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/features'
    | '/sitemap.xml'
    | '/submit'
    | '/admin'
    | '/features/$number'
    | '/giveaways/$slug'
    | '/features/'
    | '/giveaways/'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/partners'
    | '/admin/settings'
    | '/features/$number/magazine'
    | '/admin/'
    | '/admin/features/$id'
    | '/admin/features/new'
    | '/admin/giveaways/$id'
    | '/admin/giveaways/new'
    | '/admin/giveaways/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/sitemap.xml'
    | '/submit'
    | '/features/$number'
    | '/giveaways/$slug'
    | '/features'
    | '/giveaways'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/partners'
    | '/admin/settings'
    | '/features/$number/magazine'
    | '/admin'
    | '/admin/features/$id'
    | '/admin/features/new'
    | '/admin/giveaways/$id'
    | '/admin/giveaways/new'
    | '/admin/giveaways'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/features'
    | '/sitemap.xml'
    | '/submit'
    | '/_authenticated/admin'
    | '/features/$number'
    | '/giveaways/$slug'
    | '/features/'
    | '/giveaways/'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/announcements'
    | '/_authenticated/admin/partners'
    | '/_authenticated/admin/settings'
    | '/features/$number/magazine'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/features/$id'
    | '/_authenticated/admin/features/new'
    | '/_authenticated/admin/giveaways/$id'
    | '/_authenticated/admin/giveaways/new'
    | '/_authenticated/admin/giveaways/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  FeaturesRoute: typeof FeaturesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubmitRoute: typeof SubmitRoute
  GiveawaysSlugRoute: typeof GiveawaysSlugRoute
  GiveawaysIndexRoute: typeof GiveawaysIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giveaways/': {
      id: '/giveaways/'
      path: '/giveaways'
      fullPath: '/giveaways/'
      preLoaderRoute: typeof GiveawaysIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/': {
      id: '/features/'
      path: '/'
      fullPath: '/features/'
      preLoaderRoute: typeof FeaturesIndexRouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/giveaways/$slug': {
      id: '/giveaways/$slug'
      path: '/giveaways/$slug'
      fullPath: '/giveaways/$slug'
      preLoaderRoute: typeof GiveawaysSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features/$number': {
      id: '/features/$number'
      path: '/$number'
      fullPath: '/features/$number'
      preLoaderRoute: typeof FeaturesNumberRouteImport
      parentRoute: typeof FeaturesRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/features/$number/magazine': {
      id: '/features/$number/magazine'
      path: '/magazine'
      fullPath: '/features/$number/magazine'
      preLoaderRoute: typeof FeaturesNumberMagazineRouteImport
      parentRoute: typeof FeaturesNumberRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/partners': {
      id: '/_authenticated/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AuthenticatedAdminPartnersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/announcements': {
      id: '/_authenticated/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/giveaways/': {
      id: '/_authenticated/admin/giveaways/'
      path: '/giveaways'
      fullPath: '/admin/giveaways/'
      preLoaderRoute: typeof AuthenticatedAdminGiveawaysIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/giveaways/new': {
      id: '/_authenticated/admin/giveaways/new'
      path: '/giveaways/new'
      fullPath: '/admin/giveaways/new'
      preLoaderRoute: typeof AuthenticatedAdminGiveawaysNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/giveaways/$id': {
      id: '/_authenticated/admin/giveaways/$id'
      path: '/giveaways/$id'
      fullPath: '/admin/giveaways/$id'
      preLoaderRoute: typeof AuthenticatedAdminGiveawaysIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/features/new': {
      id: '/_authenticated/admin/features/new'
      path: '/features/new'
      fullPath: '/admin/features/new'
      preLoaderRoute: typeof AuthenticatedAdminFeaturesNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/features/$id': {
      id: '/_authenticated/admin/features/$id'
      path: '/features/$id'
      fullPath: '/admin/features/$id'
      preLoaderRoute: typeof AuthenticatedAdminFeaturesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminAnnouncementsRoute: typeof AuthenticatedAdminAnnouncementsRoute
  AuthenticatedAdminPartnersRoute: typeof AuthenticatedAdminPartnersRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminFeaturesIdRoute: typeof AuthenticatedAdminFeaturesIdRoute
  AuthenticatedAdminFeaturesNewRoute: typeof AuthenticatedAdminFeaturesNewRoute
  AuthenticatedAdminGiveawaysIdRoute: typeof AuthenticatedAdminGiveawaysIdRoute
  AuthenticatedAdminGiveawaysNewRoute: typeof AuthenticatedAdminGiveawaysNewRoute
  AuthenticatedAdminGiveawaysIndexRoute: typeof AuthenticatedAdminGiveawaysIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminAnnouncementsRoute: AuthenticatedAdminAnnouncementsRoute,
  AuthenticatedAdminPartnersRoute: AuthenticatedAdminPartnersRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminFeaturesIdRoute: AuthenticatedAdminFeaturesIdRoute,
  AuthenticatedAdminFeaturesNewRoute: AuthenticatedAdminFeaturesNewRoute,
  AuthenticatedAdminGiveawaysIdRoute: AuthenticatedAdminGiveawaysIdRoute,
  AuthenticatedAdminGiveawaysNewRoute: AuthenticatedAdminGiveawaysNewRoute,
  AuthenticatedAdminGiveawaysIndexRoute: AuthenticatedAdminGiveawaysIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface FeaturesNumberRouteChildren {
  FeaturesNumberMagazineRoute: typeof FeaturesNumberMagazineRoute
}

const FeaturesNumberRouteChildren: FeaturesNumberRouteChildren = {
  FeaturesNumberMagazineRoute: FeaturesNumberMagazineRoute,
}

const FeaturesNumberRouteWithChildren = FeaturesNumberRoute._addFileChildren(
  FeaturesNumberRouteChildren,
)

interface FeaturesRouteChildren {
  FeaturesNumberRoute: typeof FeaturesNumberRouteWithChildren
  FeaturesIndexRoute: typeof FeaturesIndexRoute
}

const FeaturesRouteChildren: FeaturesRouteChildren = {
  FeaturesNumberRoute: FeaturesNumberRouteWithChildren,
  FeaturesIndexRoute: FeaturesIndexRoute,
}

const FeaturesRouteWithChildren = FeaturesRoute._addFileChildren(
  FeaturesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  FeaturesRoute: FeaturesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubmitRoute: SubmitRoute,
  GiveawaysSlugRoute: GiveawaysSlugRoute,
  GiveawaysIndexRoute: GiveawaysIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
